In [ ]:
import numpy as np

a = np.arange(6).reshape(2,3) + 10  # Example usage of numpy
print(a)  # Output the random array
print('\nOutput of argmax:')
print(np.argmax(a, axis=-1))  # Example usage of argmax
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
ind
main branch edit
Main branch edit 1
main branch edit 2

[[10 11 12]
 [13 14 15]]

Output of argmax:
[2 2]


(np.int64(1), np.int64(2))

In [29]:
x = np.arange(9)
np.array_split(x, 3)  # Example usage of array_split

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [35]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)
np.concatenate((a, b.T), axis=1)
# np.concatenate((a, b), axis=None)

array([[1, 2, 5],
       [3, 4, 6]])

In [37]:
s = (2,2)
np.zeros(s)
np.array([[1, 2],[3, 4]]) == 3

array([[False, False],
       [ True, False]])